#!/usr/bin/env python
# Copyright (C) 2025 Tasos Alvas <tasos.alvas@qwertyuiopia.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generated by Shattered Pixel Dungeon Invoke Utility."""

from spdiu.tasks import ns  # noqa: F401
