#!/usr/bin/env python
# Copyright (C) 2025 Tasos Alvas <tasos.alvas@qwertyuiopia.com>
# SPDX-License-Identifier: CC0-1.0
"""Generated by the Shattered Pixel Dungeon Invoke Utility."""

from pathlib import Path
from invoke import task

# Get the spdiu root namespace.
from spdiu.spdiu import ns

# Ensure spdiu.dirs.base is an absolute path pointing to this directory.
base_path = Path(__file__).resolve().parent
ns.configure({"spdiu": {"dirs": {"base": base_path}}})
# You need this block for the directory to be movable.


@task
def hello_dungeon(c):
    """Write your own tasks in your very own "tasks.py"."""
    print("See the API documentation to get started!")
    print("https://github.com/tasosalvas/spdiu/doc/api.md")


# Uncomment this to add the task above to the namespace.
# ns.add_task(hello_dungeon)
