#!/usr/bin/env python
# Copyright (C) 2025 Tasos Alvas <tasos.alvas@qwertyuiopia.com>
# SPDX-License-Identifier: CC0-1.0
"""Generated by the Shattered Pixel Dungeon Invoke Utility."""

from pathlib import Path
from spdiu.tasks import ns

# Ensure spdiu.dirs.base is an absolute path pointing to this file.
base_path = Path(__file__).resolve().parent
ns.configure({"spdiu": {"dirs": {"base": base_path}}})
